trigger:
  branches:
    include:
      - main
  paths:
    include:
      - app
# pool:
#   name: Default
#   demands:
#     - agent.name -equals vm-myapp-agent

jobs:
  - deployment: VMDeploy
    displayName: Deploy to VM
    environment:
      name: Production
      resourceName: vm-myapp-app
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
            - script: |
                docker login --username acrmyapp888888 --password-stdin $(ACR_ADMIN_PASSWORD)
                docker pull acrmyapp888888.azurecr.io/myapp:latest
                docker run -d -p 3333:3333 acrmyapp888888.azurecr.io/myapp:latest
