trigger:
  branches:
    include:
      - main
  paths:
    include:
      - app

jobs:
  - deployment: VMDeploy
    displayName: Deploy to VM
    environment:
      name: Production
      resourceName: vm-myapp-app
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
            - script: |
                echo $(ACR_ADMIN_PASSWORD)
                echo $(ACR_ADMIN_PASSWORD) | docker login --username acrmyapp888888 --password-stdin 
                docker pull acrmyapp888888.azurecr.io/myapp:latest
                docker run -d -p 3333:3333 acrmyapp888888.azurecr.io/myapp:latest
