trigger:
  branches:
    include:
      - main
  paths:
    include:
      - app
pool:
  name: Default
  demands:
    - agent.name -equals vm-myapp-agent

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'acr-docker-others'
    repository: 'myapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
